### ISSUE TITLE
Add support for Wally

### ISSUE THREAD

**Issue by ibemember3** [imacodr/fetchu#1]
It would be nice to have Fetchu be published as a package on [Wally](https://wally.run/). 

Whilst I understand the author has made Roarn and may take issue with Fetchu being published on a competitor's platform, I believe users should not have to accommodate for two package managers just to have Fetchu, accommodate for any possible hurt feelings of the author, or go through the less-than-ideal method of copying over the latest version of Fetchu every time it updates.

I have [found a DevForum reply highlighting the author's views on why they believe Roarn should be used over Wally](https://devforum.roblox.com/t/roarn-102-a-roblox-package-manager-for-an-organized-workspace/1560554/8) - I'd like to address some of those points below:

- According to [Roarn's homepage](https://roarn.space/), the top three packages are Roact, Rodux, and TestEZ. [Wally has these](https://github.com/UpliftGames/wally-index/tree/main/roblox).
- [Wally does have package searching](https://wally.run/). (I understand this point was written when Wally at the time did not have package searching.)
- Roarn being developed before Wally is not indicative of anything other than its age.
- Unreleased features by Roarn are not indicative of Wally being less superior.

The author claims Roarn has "safer end-to-end registry requests" and "[has] a better OAuth2 system for authentication between CLI-Server." I cannot comment on the technical aspects or even the validity of these points but I would like to point out that both have no visible UX impact on a user trying to install Fetchu via Wally. I think the very fact that [Roact has a wally.toml](https://github.com/Roblox/roact/pull/314/files/94cc1f79120c7454591993908a2c13e2a5b3a773) is enough to show Wally is capable.

---

Publishing Fetchu as a package on Wally will allow Fetchu to have an official presence to a [much wider userbase](https://github.com/upliftgames/wally-index). [Whilst users currently can install Fetchu via Wally through Nightcycle's fork](https://wally.run/package/nightcycle/fetchu), it'd be nice for Fetchu to have an official author-released package on Wally.

An easy step in this direction would be simply adding a wally.toml file:

```toml
[package]
name = "imacodr/fetchu"
description = "Simplifying requests out of Roblox making HttpService easier."
version = "1.0.3"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
```

**Comment by imacodr** [comment]
Hi, there! I understand your concerns on adding Fetchu support to Wally and I completely understand. I mainly built Roarn as a learning experience to improve it, and with the current growth of Wally and its community growing even further I also agree to add a port. :)
